//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LauncherBackend.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LauncherBackend.Assets.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Project\Emfis Graphics\BAG Engine\EngineSourceCode\Launcher\LauncherBackend\Assets\BagProjectStarter.zip.
        /// </summary>
        internal static string BagTemplate {
            get {
                return ResourceManager.GetString("BagTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Project\Emfis Graphics\BAG Engine\EngineSourceCode\Launcher\LauncherBackend\Assets\GamesAppdata.json.
        /// </summary>
        internal static string File1 {
            get {
                return ResourceManager.GetString("File1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Project\Emfis Graphics\BAG Engine\EngineSourceCode\Launcher\LauncherBackend\Assets\AplicationsAppdata.json.
        /// </summary>
        internal static string File2 {
            get {
                return ResourceManager.GetString("File2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Project\Emfis Graphics\BAG Engine\EngineSourceCode\Launcher\LauncherBackend\Assets\BagProjectsAppdata.json.
        /// </summary>
        internal static string File3 {
            get {
                return ResourceManager.GetString("File3", resourceCulture);
            }
        }
    }
}
